stages:
  data_ingestion:
    cmd: python ./taxi_demand_prediction/dataset.py
    deps:
      - ./taxi_demand_prediction/dataset.py
      - ./data/raw/yellow_tripdata_2016-01.csv
      - ./data/raw/yellow_tripdata_2016-02.csv
      - ./data/raw/yellow_tripdata_2016-03.csv
    outs:
      - ./data/interim/df_without_outliers.csv
  
  extract_features:
    cmd: python ./taxi_demand_prediction/extract_features.py
    deps:
      - ./taxi_demand_prediction/extract_features.py
      - ./data/interim/df_without_outliers.csv
    params:
      - extract_features.mini_batch_kmeans.n_clusters
      - extract_features.mini_batch_kmeans.n_init
      - extract_features.mini_batch_kmeans.random_state
      - extract_features.ewma.alpha
    outs:
      - ./data/processed/resampled_data.csv
      - ./models/scaler.joblib
      - ./models/mb_kmeans.joblib
  
  feature_engineering:
    cmd: python ./taxi_demand_prediction/feature_engineering.py
    deps:
      - ./taxi_demand_prediction/feature_engineering.py
      - ./data/processed/resampled_data.csv
    outs:
      - ./data/processed/train.csv
      - ./data/processed/test.csv
  
  model_training:
    cmd: python ./taxi_demand_prediction/model_training.py
    deps:
      - ./taxi_demand_prediction/model_training.py
      - ./data/processed/train.csv
    outs:
      - ./models/encoder.joblib
      - ./models/model.joblib
